"""ok

Revision ID: 067062f4153f
Revises: 
Create Date: 2021-04-21 16:42:52.424270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067062f4153f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedbacks_id_company_fkey', 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'id_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('id_company', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('feedbacks_id_company_fkey', 'feedbacks', 'company', ['id_company'], ['id'])
    # ### end Alembic commands ###
