"""alteraçao do feedback

Revision ID: 11375054aac6
Revises: a428919c1752
Create Date: 2021-04-22 11:48:04.857813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11375054aac6'
down_revision = 'a428919c1752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedbacks', 'company', ['company_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'company_id')
    # ### end Alembic commands ###
