"""Criação da Model FeedbackModel

Revision ID: 3145905de31a
Revises: dbe55203eda0
Create Date: 2021-04-13 17:37:22.181376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3145905de31a'
down_revision = 'dbe55203eda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('user_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_company_id'], ['user_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
