"""First

Revision ID: 813da7ba14f1
Revises: 
Create Date: 2021-04-18 13:36:32.700091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813da7ba14f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=25), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('adress', sa.String(length=25), nullable=False),
    sa.Column('city', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=25), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('adress', sa.String(length=25), nullable=False),
    sa.Column('city', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=25), nullable=False),
    sa.Column('schedule', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('user_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_company_id'], ['user_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_price', sa.Integer(), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=False),
    sa.Column('date_time', sa.String(length=25), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=55), nullable=False),
    sa.Column('client_email', sa.String(length=55), nullable=False),
    sa.Column('phone', sa.String(length=55), nullable=False),
    sa.Column('service_approval', sa.String(length=55), nullable=False),
    sa.Column('user_client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_client_id'], ['user_client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('feedbacks')
    op.drop_table('user_company')
    op.drop_table('user_client')
    # ### end Alembic commands ###
