"""Create a user_company model

Revision ID: dbe55203eda0
Revises: 
Create Date: 2021-04-13 16:01:24.900601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe55203eda0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=25), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('adress', sa.String(length=25), nullable=False),
    sa.Column('city', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=25), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('adress', sa.String(length=25), nullable=False),
    sa.Column('city', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=25), nullable=False),
    sa.Column('schedule', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company')
    op.drop_table('user_client')
    # ### end Alembic commands ###
